### ISSUE TITLE
ModuleNotFoundError: No module named nvdiffrast.torch

### ISSUE THREAD

**Issue by Islaster** [flowtyone/ComfyUI-Flowty-CRM#12] opened 2024-03-17 00:18 UTC
I'm having trouble installing nvdiffrast I've downloaded the github but idk where to put it inside of this crm repo

**Comment by flowtyone** [comment] 2024-03-17 03:59
Closing, duplicate of https://github.com/flowtyone/ComfyUI-Flowty-CRM/issues/4

**Closed** 2024-03-17 04:00 UTC
